[profile.default]
src = "src"
out = "out"
libs = ["lib", "node_modules"]
test = "test"
solc = "0.8.24"
remappings = ["@fhevm/solidity/=node_modules/@fhevm/solidity/"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
